# Generated by Django 5.2 on 2025-04-15 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_user_profile_picture'),
    ]

    operations = [
    ]
