# Generated by Django 5.2 on 2025-04-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20250415_2233'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movie',
            table='api_movie',
        ),
    ]
